config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'admins/index'
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :users
  devise_for :admins

  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  def index
    @admins = Admin.all
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  layout 'admins_backoffice'
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  layout 'users_backoffice'
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/admins/index.html.erb
<h1>Listando Administradres</h1>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>id</th>
                <th>email</th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
            <tr>
                <td><%= admin.id %></td>
                <td><%= admin.email %></td>
                <td style="width: 100px">
                    <button type="button" class="btn btn-primary btn-circle">
                        <i class="fa fa-edit"></i>
                    </button>

                    <button type="button" class="btn btn-danger btn-circle">
                        <i class="fa fa-minus"></i>
                    </button>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<p> <%= link_to 'Fazer logoff [Administrador]', destroy_admin_session_path, method: :delete %> </p>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ludus</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application' %>
  <%= stylesheet_link_tag    'admins_backoffice' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">BackOffice Adminstrativo</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <%= link_to destroy_admin_session_path, method: :delete do %>
                            <i class="fa fa-sign-out fa-fw"></i> Sair
                        <% end %>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">

                        <li>
                            <%= link_to admins_backoffice_welcome_index_path do %>
                                <i class="fa fa-dashboard fa-fw"></i> Dashboard
                            <% end %>
                        </li>

                        <li>
                            <%= link_to admins_backoffice_admins_index_path do %>
                                <i class="fa fa-users fa-fw"></i> Administradores
                            <% end %>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">LAYOUT ADMINS BACKOFFICE</h1>
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins_backoffice' %>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ludus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>LAYOUT APLICATION</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ludus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>LAYOUT SITE</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ludus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>USERS APLICATION BACKOFFICE</h1>
    <%= yield %>
  </body>
</html>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in? %>
    <p>Usuario ESTÁ logado! / <%= current_user.email %> </p>
<% else %>
    <p>Usuário NÃO está logado</p>
<% end %>


<% if admin_signed_in? %>
    <p>Administrador ESTÁ logado! / <%= current_admin.email %></p>
<% else %>
    <p>Administrador NÃO está logado</p>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>

<p> <%= link_to 'Fazer logoff [Usuário]', destroy_user_session_path, method: :delete %> </p>